### PR TITLE
Support for Redmine 4.x

### PR DESCRIPTION
**Pull request by mboremski**
After some Tests this one now works for redmine 4.x
#23

### CODE REVIEW

**Comment by LittleDuke** [comment]
+1 Would be great if this was folded into base branch!

**Comment by mboremski** [comment]
Any news on this one?

**Comment by braini75** [comment]
> Any news on this one?

Hi,
is it still working for redmine 2.x and 3.x? I have no possibilities to test right now.

Thanks for your enhancement

**Comment by mboremski** [comment]
Unfortunately I also don't have a possibility to test on older versions right now..

**Pull request closed without merging**
